# permissions for end users to edit valkeyclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: valkey-cluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: valkeycluster-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - valkeyclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - valkeyclusters/status
  verbs:
  - get
