apiVersion: cache.example.com/v1alpha1
kind: Memcached
metadata:
  labels:
    app.kubernetes.io/name: valkey-cluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: memcached-sample
spec:
  size: 3
  containerPort: 11211
