name: dagger

permissions: write-all

on:
  push:
    branches: [master]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - name: Env
        run: |
          # ACTIONS_RUNTIME_TOKEN, ACTIONS_RUNTIME_URL should be exposed
          env|sort
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: "latest"
          module: ./
          args: create-git-hub-release --gh-token=env://GITHUB_TOKEN
          cache_config: "type=gha,mode=max,url=${{ env.ACTIONS_CACHE_URL }},token=${{ env.ACTIONS_RUNTIME_TOKEN }}"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
